Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest:5000, host:5000
    config.vm.synced_folder "../", "/mycluster", owner: "root", group: "root"

    config.vm.provision :shell do |sh|
        sh.inline = <<-EOF
            # TODO Replace this by a separate script file
            echo "pipedrive:any provisioning scripts should go here"
         EOF
    end

    config.vm.provision "chef_solo" do |chef|
          chef.arguments = "--chef-license accept"
          chef.cookbooks_path = "chef/cookbooks" 
          chef.add_recipe "mycluster::default"
     end
end