version: '3'
services:
  manager:
    build: 
      context: ../manager/.
      dockerfile: manager.Dockerfile
    ports:
     - "5000:5000"
    env_file:
    - mycluster.env
  redis:
    image: "redis:alpine"
  worker:
    image: "docker:dind"
    privileged: true
    depends_on:
      - manager
  monitor:
    build: 
      context: ../manager/.
      dockerfile: monitor.Dockerfile
    env_file:
    - mycluster.env